"""Kernel PCA and one-class SVM using the same records and scoring interface."""
from pathlib import Path

import joblib
import numpy as np
from sklearn.decomposition import KernelPCA
from sklearn.svm import OneClassSVM

from .data import write_json
from .transforms import InputTransform


class ClassicalPredictor:
    def __init__(self, estimator, transform, method, view_shape, parameters, head=None, device=None):
        self.estimator, self.transform, self.method = estimator, transform, method
        self.view_shape, self.parameters = tuple(view_shape), parameters
        self.head, self.device = head, device

    def scores(self, store, ids):
        if store.view_shape != self.view_shape or store.manifest["parameters"] != self.parameters:
            raise ValueError("Prediction features differ from the trained preprocessing recipe")
        raw, labels, names = store.flat_views(ids)
        values = self.transform.apply(raw)
        if self.method == "ocsvm":
            scores = -self.estimator.decision_function(values)
        elif self.method == "kpca_classifier":
            from .training import head_scores
            scores = head_scores(self.head, self.estimator.transform(values).astype(np.float32), self.device)
        else:
            reconstruction = self.estimator.inverse_transform(self.estimator.transform(values))
            scores = np.linalg.norm(values - reconstruction, axis=1)
        counters, rows = {}, []
        for name, label, score in zip(names, labels, scores):
            index = counters.get(name, 0)
            counters[name] = index + 1
            rows.append({"record_id": name, "label": int(label), "observation": index, "score": float(score)})
        return rows

    def save(self, folder):
        folder = Path(folder)
        joblib.dump({"estimator": self.estimator, "transform": self.transform.to_dict(),
                     "method": self.method, "view_shape": self.view_shape, "parameters": self.parameters},
                    folder / "baseline.joblib")
        if self.head is not None:
            import torch
            torch.save({k: v.detach().cpu() for k, v in self.head.state_dict().items()}, folder / "classifier.pt")
            write_json(folder / "classifier_architecture.json", {
                "input_dim": self.estimator.eigenvectors_.shape[1],
                "hidden_dims": [layer.out_features for layer in self.head.network if isinstance(layer, torch.nn.Linear)][:-1]})

    @classmethod
    def load(cls, folder, device="cpu"):
        """Load an artifact generated by this project (joblib files must be trusted)."""
        import json
        folder = Path(folder)
        metadata = joblib.load(folder / "baseline.joblib")
        head, target = None, None
        if metadata["method"] == "kpca_classifier":
            import torch
            from .models import BinaryClassifier
            from .training import device_for
            structure = json.loads((folder / "classifier_architecture.json").read_text())
            head = BinaryClassifier(structure["input_dim"], structure["hidden_dims"])
            head.load_state_dict(torch.load(folder / "classifier.pt", map_location="cpu", weights_only=True))
            target = device_for(device)
            head = head.to(target).eval()
        return cls(metadata["estimator"], InputTransform(**metadata["transform"]), metadata["method"],
                   metadata["view_shape"], metadata["parameters"], head, target)


def fit_classical(store, train_ids, config):
    if store.representation != "rr" or len(store.view_shape) != 1:
        raise ValueError("Classical baselines require an RR feature store")
    normal_ids = [name for name in train_ids if store.by_id[name]["label"] == 0]
    raw, _, _ = store.flat_views(normal_ids)
    if len(raw) < 3:
        raise ValueError("At least three normal training views are required")
    transform = InputTransform(config.model.rr_statistics, config.model.standardize).fit(raw)
    values = transform.apply(raw)
    if config.method == "ocsvm":
        estimator = OneClassSVM(nu=config.model.svm_nu, kernel="rbf", gamma="auto").fit(values)
    else:
        estimator = KernelPCA(n_components=min(config.model.kpca_components, len(values) - 1),
                              kernel="rbf", fit_inverse_transform=True, alpha=config.model.kpca_alpha,
                              eigen_solver="arpack", random_state=config.seed).fit(values)
    head, target, history = None, None, []
    if config.method == "kpca_classifier":
        from .training import device_for, fit_head
        data, labels, _ = store.flat_views(train_ids)
        embeddings = estimator.transform(transform.apply(data)).astype(np.float32)
        head, history = fit_head(embeddings, labels, config)
        target = device_for(config.training.device)
    return ClassicalPredictor(estimator, transform, config.method, store.view_shape,
                              store.manifest["parameters"], head, target), history
